[package]
name = "gt-project"
description = "GloomTunes Studio: project editing, undo/redo and persistence."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true


[dependencies]
gt-core.workspace = true
symphonia.workspace = true
rubato.workspace = true

[dev-dependencies]
hound.workspace = true
