[package]
name = "gt-engine"
description = "GloomTunes Studio: real-time audio engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
gt-core.workspace = true
gt-dsp.workspace = true
rtrb.workspace = true

[dev-dependencies]
assert_no_alloc.workspace = true
