[package]
name = "gt-dsp"
description = "GloomTunes Studio: pure DSP building blocks."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lints]
workspace = true


[dev-dependencies]
criterion.workspace = true
insta.workspace = true

[[bench]]
name = "synth"
harness = false
